<?php
if( function_exists('acf_add_local_field_group') ):
	
	acf_add_local_field_group(array (
		'key' => 'group_57d8db9543c0a',
		'title' => 'Submit an Article',
		'fields' => array (
			array (
				'key' => 'field_57df8bc97e37f',
				'label' => 'Featured Photo',
				'name' => 'eca_featured_photo_type',
				'type' => 'select',
				'instructions' => 'The featured photo will be displayed at the top of your article, and is also used on article listing pages.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'Choose an image from the stock photo library' => 'Choose an image from the stock photo library',
					'Upload my own image' => 'Upload my own image',
				),
				'default_value' => array (
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'disabled' => 0,
				'readonly' => 0,
				'return_format' => 'value',
			),
			array (
				'key' => 'field_57da1c73315f5',
				'label' => 'Stock Featured Photo',
				'name' => 'eca_featured_photo',
				'type' => 'stock_photo',
				'instructions' => 'Select an image from our stock photo gallery below.',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57df8bc97e37f',
							'operator' => '==',
							'value' => 'Choose an image from the stock photo library',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'font_size' => 14,
			),
			array (
				'key' => 'field_57df8bff7e380',
				'label' => 'Custom Featured Photo',
				'name' => 'eca_featured_photo_custom',
				'type' => 'image',
				'instructions' => 'Your photo must be at least 730&times;350 (in pixels), and less than 2mb in filesize. Allowed file types are PNG and JPG.',
				'required' => 1,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57df8bc97e37f',
							'operator' => '==',
							'value' => 'Upload my own image',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'thumbnail',
				'library' => 'uploadedTo',
				'min_width' => 730,
				'min_height' => 350,
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => 3,
				'mime_types' => 'jpg, jpeg, png, JPG, JPEG, PNG',
			),
			array (
				'key' => 'field_57f59e0a9f7bd',
				'label' => 'Publish Date',
				'name' => 'eca_publish_date',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'Publish Immediately' => 'Publish Immediately',
					'Scheduled' => 'Scheduled',
				),
				'default_value' => array (
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'disabled' => 0,
				'readonly' => 0,
				'return_format' => 'value',
			),
			array (
				'key' => 'field_57f59d7658689',
				'label' => 'Schedule On',
				'name' => 'schedule_on',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57f59e0a9f7bd',
							'operator' => '==',
							'value' => 'Scheduled',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'F j, Y',
				'return_format' => 'Ymd',
				'first_day' => 0,
			),
			array (
				'key' => 'field_57d8dc01ae949',
				'label' => 'Keywords / Tags',
				'name' => 'eca_article_tags',
				'type' => 'taxonomy',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => 'post_tag',
				'field_type' => 'multi_select',
				'allow_null' => 0,
				'add_term' => 1,
				'save_terms' => 1,
				'load_terms' => 1,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_58ad19d298374',
				'label' => 'SEO Title',
				'name' => 'eca_seo_title',
				'type' => 'text',
				'instructions' => 'The SEO title should be similar to or the same as the site title. You should leave this empty in most cases, unless the title is too long and can be reduced.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58ad1dc498376',
				'label' => 'SEO URL Slug',
				'name' => 'eca_seo_slug',
				'type' => 'text',
				'instructions' => 'A slug is the last part of the URL that identifies the page. You should not include the domain name in this field. Example slug: <strong>5-tips-to-writing-articles</strong>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58ad1db898375',
				'label' => 'SEO Description',
				'name' => 'eca_seo_description',
				'type' => 'textarea',
				'instructions' => 'This is the excerpt that Google will display when your article is found. This paragraph should have relevance with the content found in the page.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 2,
				'new_lines' => '',
			),
			array (
				'key' => 'field_58ad1dd998377',
				'label' => 'Focus Keyword',
				'name' => 'eca_focus_keyword',
				'type' => 'text',
				'instructions' => 'This is the term of phrase that you want your article to rank for in Google. Google does not see this keyword directly, but ensuring that you have used a consistent focus keyword will help improve the search engine relevance for visitors who search for the phrase.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_58ad1dfe98379',
				'label' => 'Google Search Preview',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'new_lines' => '',
				'esc_html' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => 0,
		'description' => '',
	));

endif;